### ISSUE TITLE
Category Layout question

### ISSUE THREAD

**Issue by njt1982** [minddust/minddust.github.io#10]
Hi,

Loving your tag and category tutorials; just what I was looking for! (Although #9 is an interesting question...)

My question is about the layout:
https://github.com/minddust/minddust.github.io/blob/master/_layouts/blog_by_category.html

In here you treat the my_categories as a hash, rather than an array. For me, that collection is an array; I cannot access them by slug, but instead by numeric ID... Eg:

`site.categories[0].slug` -- works
`site.categories['example'].slug` -- does not work

Also youre collection is `my_categories` but you use `categories` in `site`?

**Comment by njt1982** [comment]
Genuinely confused as to where `.tag` and `.categories` is defined for your site, given the collection names are `my_categories` and `my_tags`....

https://github.com/minddust/minddust.github.io/search?q=categories&type=Code&utf8=%E2%9C%93

**Comment by njt1982** [comment]
Ahhh its a Jekyll variable? https://jekyllrb.com/docs/variables/

**Comment by njt1982** [comment]
AHH! I see!

So it's critical that you use `my_categories`. I named my collection `categories`, but that collided with the internal variable namespace.

Essentially, your method relies on generating the category pages using my_categories, but pairing them up to categories set on the posts.

**Comment by minddust** [comment]
@njt1982 thats totally correct! maybe i should explain this in the post in a more detail way.

**Comment by njt1982** [comment]
Yeah, could maybe do with a paragraph on that. Your post ranks highly for that search topic. 😉
