### ISSUE TITLE
Add post = page assignment

### ISSUE THREAD

**Issue by bertmelis** [minddust/minddust.github.io#11]
I've read [your post](http://www.minddust.com/post/alternative-tags-and-categories-on-github-pages/) about categories and tags on github pages. It was exactly what I was looking for. However, I could only get it working untill I saw that I've missed something.

You have to add this: `{% assign post = page %}` at the top of the post layout. Alternatively, you could replace `post` by `page` in the subsequent code. I know the [earlier post](http://www.minddust.com/post/tags-and-categories-on-github-pages/) does contain this statement. But when writing code examples, the code should be complete.

**Comment by MarcelReig** [comment]
Thanks Bert your comment helped me! This is an important point for newbies like me :)
