### ISSUE TITLE
Blog post leaves out crucial information

### ISSUE THREAD

**Issue by cdr255** [minddust/minddust.github.io#4]
Hi there,

In your blog post, *HOW TO USE TAGS AND CATEGORIES ON GITHUB PAGES WITHOUT PLUGINS*, you supply an incomplete example of the code needed to set the system up. In the implementation of the website, you have one extra line above what you have mirrored in the post:

`{% assign post = page %}`

This line is crucial to the rest of the code working, since (at least as of now) Jekyll uses 'page' instead of 'post'.

After I added that line, implementing the rest was extremely easy and very well documented, especially with the full implementation available for perusal. I am very grateful that you took the time to figure this out, and thought you might be unaware of the above omission.

**Comment by minddust** [comment]
hey @cdr255 

thanks for the hint. will check this out in a sec. guess i just missed it while copy+pasting the code ;-)

**Comment by minddust** [comment]
updated :smile: 
thanks again :+1:
special reward: :beer:
